name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install GNOME Shell extension tools
        run: sudo apt-get update && sudo apt-get install -y gnome-shell-extensions
      
      - name: Build extension for CI
        run: npm run ci-build-extension
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zellij-theme-switcher
          path: dist/zellij-theme-switcher@angelsen.github.io.shell-extension.zip
  
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zellij-theme-switcher
      
      - name: Ensure dist directory exists
        run: mkdir -p dist
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/zellij-theme-switcher@angelsen.github.io.shell-extension.zip
          draft: false
          prerelease: true
          generate_release_notes: true
      
      # No need to publish to NPM, we'll use GitHub releases directly